name: Check

on:
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          cache: true
          install: false
      - uses: oven-sh/setup-bun@v2
      - run: pnpm install --frozen-lockfile
      - run: bun check:tsc
