name: Check

on:
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: oven-sh/setup-bun@v2
      - run: pnpm install --frozen-lockfile
      - run: bun check:tsc
